/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udec.vista;

import com.udec.persistencia.Conductor;
import com.udec.persistencia.Log;
import com.udec.persistencia.Vehiculo;
import com.udec.controlador.LogJpaController;
import com.udec.persistencia.Recorrido;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Insets;
import java.awt.Toolkit;
import java.beans.Beans;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.LineNumberReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SpinnerDateModel;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Oscar
 */
public class RecorridoForm extends JInternalFrame {

    JFileChooser fc;

    public RecorridoForm() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        fc = new JFileChooser();

    }

    TableCellRenderer tableCellRenderer = new DefaultTableCellRenderer() {

        SimpleDateFormat f = new SimpleDateFormat("HH:mm:ss");

        public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            if (value instanceof Date) {
                value = f.format(value);
            }
            return super.getTableCellRendererComponent(table, value, isSelected,
                    hasFocus, row, column);
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyecto?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Recorrido r");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        vehiculoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Vehiculo v");
        vehiculoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : vehiculoQuery.getResultList();
        conductorQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Conductor c");
        conductorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : conductorQuery.getResultList();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        nombreLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        horaSalidaProgramadaLabel = new javax.swing.JLabel();
        horaLlegadaProgramadaLabel = new javax.swing.JLabel();
        horaInicioLabel = new javax.swing.JLabel();
        horaFinalizacionLabel = new javax.swing.JLabel();
        otrosDatosLabel = new javax.swing.JLabel();
        vehiculoidVehiculoLabel = new javax.swing.JLabel();
        conductoridConductorLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        otrosDatosField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner(new SpinnerDateModel());
        jSpinner2 = new javax.swing.JSpinner(new SpinnerDateModel());
        jSpinner3 = new javax.swing.JSpinner(new SpinnerDateModel());
        jSpinner4 = new javax.swing.JSpinner(new SpinnerDateModel());
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        FormListener formListener = new FormListener();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Recorridos");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaSalidaProgramada}"));
        columnBinding.setColumnName("Hora Salida Programada");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaLlegadaProgramada}"));
        columnBinding.setColumnName("Hora Llegada Programada");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaInicio}"));
        columnBinding.setColumnName("Hora Inicio");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaFinalizacion}"));
        columnBinding.setColumnName("Hora Finalizacion");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vehiculoidVehiculo.placa}"));
        columnBinding.setColumnName("Vehiculo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${conductoridConductor.primerNombre}"));
        columnBinding.setColumnName("Conductor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${otrosDatos}"));
        columnBinding.setColumnName("Otros Datos");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);
        masterTable.getColumnModel ().getColumn(2).setCellRenderer(tableCellRenderer);
        masterTable.getColumnModel ().getColumn(3).setCellRenderer(tableCellRenderer);
        masterTable.getColumnModel ().getColumn(4).setCellRenderer(tableCellRenderer);
        masterTable.getColumnModel ().getColumn(5).setCellRenderer(tableCellRenderer);

        nombreLabel.setText("Nombre:");

        fechaLabel.setText("Fecha:");

        horaSalidaProgramadaLabel.setText("Hora Salida Programada:");

        horaLlegadaProgramadaLabel.setText("Hora Llegada Programada:");

        horaInicioLabel.setText("Hora Inicio:");

        horaFinalizacionLabel.setText("Hora Finalizacion:");

        otrosDatosLabel.setText("Otros Datos:");

        vehiculoidVehiculoLabel.setText("Vehiculo:");

        conductoridConductorLabel.setText("Conductor:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nombre}"), nombreField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nombreField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.otrosDatos}"), otrosDatosField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), otrosDatosField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        saveButton.setText("Guardar cambios");
        saveButton.addActionListener(formListener);

        refreshButton.setText("Actualizar");
        refreshButton.addActionListener(formListener);

        newButton.setText("Nuevo");
        newButton.addActionListener(formListener);

        deleteButton.setText("Eliminar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);

        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(jSpinner1, "HH:mm:ss");
        jSpinner1.setEditor(timeEditor);

        JSpinner.DateEditor timeEditor2 = new JSpinner.DateEditor(jSpinner2, "HH:mm:ss");
        jSpinner2.setEditor(timeEditor2);

        JSpinner.DateEditor timeEditor3 = new JSpinner.DateEditor(jSpinner3, "HH:mm:ss");
        jSpinner3.setEditor(timeEditor3);

        JSpinner.DateEditor timeEditor4 = new JSpinner.DateEditor(jSpinner4, "HH:mm:ss");
        jSpinner4.setEditor(timeEditor4);

        jComboBox1.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Vehiculo) {
                    Vehiculo mec = (Vehiculo)value;
                    setText(mec.getPlaca());
                }
                return this;
            }
        });

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vehiculoList, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.vehiculoidVehiculo}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBox2.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Conductor) {
                    Conductor mec = (Conductor)value;
                    setText(mec.getPrimerNombre());
                }
                return this;
            }
        });

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, conductorList, jComboBox2);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.conductoridConductor}"), jComboBox2, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBox2.addActionListener(formListener);

        jTextField1.setEditable(false);

        jButton1.setText("Examinar");
        jButton1.addActionListener(formListener);

        jButton2.setText("Importar Log");
        jButton2.addActionListener(formListener);

        jTable1.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.logList}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, eLProperty, jTable1);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tiempo}"));
        columnBinding.setColumnName("Tiempo");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${canal}"));
        columnBinding.setColumnName("Canal");
        columnBinding.setColumnClass(Short.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroDato}"));
        columnBinding.setColumnName("Numero Dato");
        columnBinding.setColumnClass(Short.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${crc}"));
        columnBinding.setColumnName("Crc");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.logList}"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("model"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setCellRenderer(tableCellRenderer);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vehiculoidVehiculoLabel)
                                .addGap(429, 429, 429)
                                .addComponent(conductoridConductorLabel)
                                .addGap(80, 80, 80)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel)
                                    .addComponent(horaSalidaProgramadaLabel)
                                    .addComponent(horaInicioLabel)
                                    .addComponent(otrosDatosLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinner3)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                    .addComponent(nombreField, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(otrosDatosField))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(horaLlegadaProgramadaLabel)
                                            .addComponent(fechaLabel)
                                            .addComponent(horaFinalizacionLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSpinner2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(newButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(refreshButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, newButton, refreshButton, saveButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSpinner1, jSpinner3, nombreField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombreLabel)
                        .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fechaLabel)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horaSalidaProgramadaLabel)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaLlegadaProgramadaLabel)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horaInicioLabel)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaFinalizacionLabel)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiculoidVehiculoLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conductoridConductorLabel)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otrosDatosLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(otrosDatosField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saveButton)
                                .addComponent(refreshButton)
                                .addComponent(deleteButton)
                                .addComponent(newButton)))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horaSalidaProgramada}"), jSpinner1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        binding.setSourceNullValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horaLlegadaProgramada}"), jSpinner2, org.jdesktop.beansbinding.BeanProperty.create("value"));
        binding.setSourceNullValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horaInicio}"), jSpinner3, org.jdesktop.beansbinding.BeanProperty.create("value"));
        binding.setSourceNullValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horaFinalizacion}"), jSpinner4, org.jdesktop.beansbinding.BeanProperty.create("value"));
        binding.setSourceNullValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.fecha}"), jDateChooser1, org.jdesktop.beansbinding.BeanProperty.create("date"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jDateChooser1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == saveButton) {
                RecorridoForm.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                RecorridoForm.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                RecorridoForm.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                RecorridoForm.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jComboBox2) {
                RecorridoForm.this.jComboBox2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                RecorridoForm.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                RecorridoForm.this.jButton2ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<com.udec.persistencia.Recorrido> toRemove = new ArrayList<com.udec.persistencia.Recorrido>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            com.udec.persistencia.Recorrido r = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(r);
            entityManager.remove(r);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        com.udec.persistencia.Recorrido r = new com.udec.persistencia.Recorrido();
        r.setHoraFinalizacion(new Date());
        r.setHoraInicio(new Date());
        r.setHoraLlegadaProgramada(new Date());
        r.setHoraSalidaProgramada(new Date());
        entityManager.persist(r);
        list.add(r);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<com.udec.persistencia.Recorrido> merged = new ArrayList<com.udec.persistencia.Recorrido>(list.size());
            for (com.udec.persistencia.Recorrido r : list) {
                merged.add(entityManager.merge(r));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String ruta = file.getAbsolutePath();
            jTextField1.setText(ruta);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        ProgressBar barra = new ProgressBar();
        //barra.setModal(true);
        barra.setVisible(true);
        barra.ejecutarTarea();
        //barra.dispose();
        //ingreserDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void ingreserDatos() {

        int totalLineas = 0;
        int selected = -1;
        int numeroLinea = -1;
        String nombreDeArchivo;
        String strLinea;
        Recorrido r;
        File file;
        FileReader reader;
        //BufferedReader buffer;
        LineNumberReader buffer;
        LogJpaController ljc;
        Log l;

        try {

            ljc = new LogJpaController();
            l = new Log();
            selected = masterTable.getSelectedRow();
            r = list.get(masterTable.convertRowIndexToModel(selected));
            nombreDeArchivo = jTextField1.getText();
            totalLineas = countLines(nombreDeArchivo);

            /*
             FileInputStream fstream = new FileInputStream(jTextField1.getText());
             // Creamos el objeto de entrada
             DataInputStream entrada = new DataInputStream(fstream);
             */
            // Abrimos el archivo
            file = new File(nombreDeArchivo);
            reader = new FileReader(file);

            // Creamos el Buffer de Lectura
            //buffer = new BufferedReader(reader);
            buffer = new LineNumberReader(reader);

            // Leer el archivo linea por linea
            while ((strLinea = buffer.readLine()) != null) {
                numeroLinea = buffer.getLineNumber() / 2;

                if (strLinea.isEmpty()) {
                    continue;
                }

                String aux[] = strLinea.split(":");

                int dia = Integer.parseInt(aux[0].trim(), 16);
                int mes = Integer.parseInt(aux[1].trim(), 16);
                int anio = Integer.parseInt(aux[2].trim(), 16);
                int horas = Integer.parseInt(aux[3].trim(), 16);
                int minutos = Integer.parseInt(aux[4].trim(), 16);
                int segundos = Integer.parseInt(aux[5].trim(), 16);
                short consecutivo_sensor = Short.parseShort(aux[6].trim(), 16);
                short dato = Short.parseShort(aux[7].trim(), 16);
                int valor = Integer.parseInt(aux[8].trim(), 16);
                int crc = Integer.parseInt(aux[9].trim(), 16);

                String strDia = (dia > 9 ? "" + dia : "0" + dia);
                String strMes = (mes > 9 ? "" + mes : "0" + mes);
                String strAnio = (anio > 9 ? "" + anio : "0" + anio);

                String strHoras = (horas > 9 ? "" + horas : "0" + horas);
                String strMinutos = (minutos > 9 ? "" + minutos : "0" + minutos);
                String strSegundos = (segundos > 9 ? "" + segundos : "0" + segundos);

                l.setCanal(consecutivo_sensor);
                l.setNumeroDato(dato);
                l.setValor(valor);
                l.setCrc(crc);
                l.setRecorridoidRecorrido(r);

                SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yy");
                String strFecha = "" + strDia + "/" + strMes + "/" + strAnio;
                Date fecha = null;

                fecha = formatoDelTexto.parse(strFecha);

                l.setFecha(fecha);

                /*SimpleDateFormat formatoDelTexto2 = new SimpleDateFormat("yy/MM/dd hh:mm:ss");
                 String strHora = "" + strDia + "/" + strMes + "/" + strAnio + " " + strHoras + ":" + strMinutos + ":" + strSegundos;*/
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(fecha);
                calendar.add(Calendar.HOUR_OF_DAY, horas);
                calendar.add(Calendar.MINUTE, minutos);
                calendar.add(Calendar.SECOND, segundos);

                Date hora = null;
                //hora = formatoDelTexto.parse(strHora);
                hora = calendar.getTime();
                l.setTiempo(hora);

                //ljc.create(l);
                System.err.println("=== " + numeroLinea + " de " + totalLineas + " ==> " + l.toString());
            }
            // Cerramos el archivo
            //entrada.close();
            buffer.close();
            reader.close();
            System.err.println("ha terminado!!!!");
        } catch (IOException | NumberFormatException | ParseException e) {
            System.err.println("Ocurrio un error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<com.udec.persistencia.Conductor> conductorList;
    private javax.persistence.Query conductorQuery;
    private javax.swing.JLabel conductoridConductorLabel;
    private javax.swing.JButton deleteButton;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel horaFinalizacionLabel;
    private javax.swing.JLabel horaInicioLabel;
    private javax.swing.JLabel horaLlegadaProgramadaLabel;
    private javax.swing.JLabel horaSalidaProgramadaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private java.util.List<com.udec.persistencia.Recorrido> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField otrosDatosField;
    private javax.swing.JLabel otrosDatosLabel;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private java.util.List<com.udec.persistencia.Vehiculo> vehiculoList;
    private javax.persistence.Query vehiculoQuery;
    private javax.swing.JLabel vehiculoidVehiculoLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public class ProgressBar extends JDialog implements PropertyChangeListener {

        private JProgressBar progressBar;
        private JTextArea taskOutput;
        private Task task;

        public ProgressBar() {

            progressBar = new JProgressBar(0, 100);
            progressBar.setValue(0);
            progressBar.setStringPainted(true);

            taskOutput = new JTextArea(5, 20);
            taskOutput.setMargin(new Insets(5, 5, 5, 5));
            taskOutput.setEditable(false);

            JPanel panel = new JPanel();

            panel.add(progressBar);

            this.setLayout(new BorderLayout());
            add(panel, BorderLayout.PAGE_START);
            add(new JScrollPane(taskOutput), BorderLayout.CENTER);
            setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
            this.pack();

        }

        class Task extends SwingWorker<Void, Void> {

            @Override
            public Void doInBackground() {
                int totalLineas = 0;
                int selected = -1;
                int numeroLinea = -1;
                String nombreDeArchivo;
                String strLinea;
                Recorrido r;
                File file;
                FileReader reader;
                LineNumberReader buffer;
                LogJpaController ljc;
                Log l;

                try {

                    ljc = new LogJpaController();
                    l = new Log();
                    selected = masterTable.getSelectedRow();
                    r = list.get(masterTable.convertRowIndexToModel(selected));
                    nombreDeArchivo = jTextField1.getText();
                    totalLineas = countLines(nombreDeArchivo);

                    // Abrimos el archivo
                    file = new File(nombreDeArchivo);
                    reader = new FileReader(file);

                    // Creamos el Buffer de Lectura
                    //buffer = new BufferedReader(reader);
                    buffer = new LineNumberReader(reader);

                    progressBar.setMaximum(totalLineas);

                    // Leer el archivo linea por linea
                    while ((strLinea = buffer.readLine()) != null) {
                        numeroLinea = buffer.getLineNumber() / 2;

                        if (strLinea.isEmpty()) {
                            continue;
                        }

                        String aux[] = strLinea.split(":");

                        int dia = Integer.parseInt(aux[0].trim(), 16);
                        int mes = Integer.parseInt(aux[1].trim(), 16);
                        int anio = Integer.parseInt(aux[2].trim(), 16);
                        int horas = Integer.parseInt(aux[3].trim(), 16);
                        int minutos = Integer.parseInt(aux[4].trim(), 16);
                        int segundos = Integer.parseInt(aux[5].trim(), 16);
                        short consecutivo_sensor = Short.parseShort(aux[6].trim(), 16);
                        short dato = Short.parseShort(aux[7].trim(), 16);
                        int valor = Integer.parseInt(aux[8].trim(), 16);
                        int crc = Integer.parseInt(aux[9].trim(), 16);

                        String strDia = (dia > 9 ? "" + dia : "0" + dia);
                        String strMes = (mes > 9 ? "" + mes : "0" + mes);
                        String strAnio = (anio > 9 ? "" + anio : "0" + anio);

                        String strHoras = (horas > 9 ? "" + horas : "0" + horas);
                        String strMinutos = (minutos > 9 ? "" + minutos : "0" + minutos);
                        String strSegundos = (segundos > 9 ? "" + segundos : "0" + segundos);

                        l.setCanal(consecutivo_sensor);
                        l.setNumeroDato(dato);
                        l.setValor(valor);
                        l.setCrc(crc);
                        l.setRecorridoidRecorrido(r);

                        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yy");
                        String strFecha = "" + strDia + "/" + strMes + "/" + strAnio;
                        Date fecha = null;

                        fecha = formatoDelTexto.parse(strFecha);

                        l.setFecha(fecha);

                        Calendar calendar = Calendar.getInstance();
                        calendar.setTime(fecha);
                        calendar.add(Calendar.HOUR_OF_DAY, horas);
                        calendar.add(Calendar.MINUTE, minutos);
                        calendar.add(Calendar.SECOND, segundos);

                        Date hora = null;

                        hora = calendar.getTime();
                        l.setTiempo(hora);

                        ljc.create(l);
                        System.err.println("=== " + numeroLinea + " de " + totalLineas + " ==> " + l.toString());
                        taskOutput.append("\nLinea " + numeroLinea + " de " + totalLineas);
                        progressBar.setValue(numeroLinea);
                        //setProgress((numeroLinea/totalLineas));
                    }

                    // Cerramos el archivo
                    buffer.close();
                    reader.close();
                    System.err.println("ha terminado!!!!");

                } catch (IOException | NumberFormatException | ParseException e) {
                    System.err.println("Ocurrio un error: " + e.getMessage());
                    taskOutput.append("\nError al cargar el archivo");
                    e.printStackTrace();
                }
                return null;
            }

            @Override
            public void done() {
                Toolkit.getDefaultToolkit().beep();
                taskOutput.append("\n=== Archivo cargado ===");
                JOptionPane.showMessageDialog(ProgressBar.this, "Carga terminada");
                //ProgressBar.this.dispose();
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        }

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if ("progress" == evt.getPropertyName()) {
                int progress = (Integer) evt.getNewValue();
                progressBar.setValue(progress);
                taskOutput.append(String.format("Completed %d%% of task.\n", task.getProgress()));
            }
        }

        public void ejecutarTarea() {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            task = new Task();
            task.addPropertyChangeListener(ProgressBar.this);
            task.execute();

        }

    }

    public static int countLines(String filename) throws IOException {
        InputStream is = new BufferedInputStream(new FileInputStream(filename));
        try {
            byte[] c = new byte[1024];
            int count = 0;
            int readChars = 0;
            boolean empty = true;
            while ((readChars = is.read(c)) != -1) {
                empty = false;
                for (int i = 0; i < readChars; ++i) {
                    if (c[i] == '\n') {
                        ++count;
                    }
                }
            }
            return (count == 0 && !empty) ? 1 : count;
        } finally {
            is.close();
        }
    }
}
